#!/bin/bash
#           _          _                                 
#  ___  ___| |____    | |__  ___ _ ____      ___ __ ___  
# / __|/ _ \ |_  /____| '_ \/ __| '_ \ \ /\ / / '_ ` _ \ 
# \__ \  __/ |/ /_____| |_) \__ \ |_) \ V  V /| | | | | |
# |___/\___|_/___|    |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#                               |_|                      

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config top_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

bspc config focus_follows_pointer       true
bspc config history_aware_focus         true
bspc config focused_border_color        "#8AB4F8"
bspc config normal_border_color         "#242424"
bspc config presel_feedback_color       "#8AB4F8"

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         3
bspc config window_gap           12
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gnome_pie manage=off layer=above border=off focus=off locked=on marked=on sticky=on
bspc rule -a Peek focus=on state=floating center=on rectangle=600x480
# bspc rule -a Emoji-keyboard focus=on state=floating center=on rectangle=600x400+1500+52
bspc rule -a Magnus focus=on state=floating center=on rectangle=800x600+560+240
bspc rule -a Kupfer.py focus=on center=on
bspc rule -a Gnome-calculator focus=on center=on state=floating
bspc rule -a kitty:*:scratchpad sticky=on state=floating rectangle=1600x280+160+38

export QT_STYLE_OVERRIDE=kvantum

# if [[ $1 -gt 0 ]];
# then
# [[ -z $(pidof plank) ]] && plank || pkill plank ; plank &
# else
#   xfce4-terminal & plank &
# fi

setxkbmap -option "caps:escape" &
feh --bg-scale ~/Pictures/Wallpapers/wall.png &
kupfer --no-splash &
xsetroot -cursor_name left_ptr &
bspc config -d 1 &
xset r rate 260 60 &
unclutter &
dunst -lb "#242424b2" -nb "#242424b2" -cb "#242424b2" -lfr "#8AB4F8" -nfr "#8AB4F8" -cfr "#8AB4F8" -lf "#f7f7f7" -nf "#f7f7f7" -cf "#f7f7f7" -lh "#FF1744" -nh "#FF1744" -ch "#FF1744"&
picom --config ~/.config/picom/picomrc --experimental -d -b &
# [[ -z $(pidof gnome-pie) ]] && gnome-pie &
[[ -z $(pidof polybar) ]] && polybar bspwm_gnome || pkill polybar ; polybar bspwm_gnome &

while pgrep -u $UID -f bspwm_window_titles >/dev/null; do pkill -f bspwm_window_titles; done
bspwm_window_titles &
