#!/bin/bash
#           _          _                                 
#  ___  ___| |____    | |__  ___ _ ____      ___ __ ___  
# / __|/ _ \ |_  /____| '_ \/ __| '_ \ \ /\ / / '_ ` _ \ 
# \__ \  __/ |/ /_____| |_) \__ \ |_) \ V  V /| | | | | |
# |___/\___|_/___|    |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#                               |_|                      

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config top_padding 26
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

bspc config focus_follows_pointer       true
bspc config history_aware_focus         true
bspc config focused_border_color        "#8AB4F8"
bspc config normal_border_color         "#242424"
bspc config presel_feedback_color       "#8AB4F8"

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         3
bspc config window_gap           12
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

#bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Screenkey manage=off

bspc rule -a Plank manage=off layer=above border=off focus=off locked=on #marked=on sticky=on
bspc rule -a Peek focus=on state=floating center=on rectangle=800x600
bspc rule -a Emoji-keyboard focus=on state=floating center=on rectangle=600x400+1500+52
bspc rule -a Magnus focus=on state=floating center=on rectangle=800x600+560+240
bspc rule -a Kupfer.py focus=on center=on
bspc rule -a Gnome-calculator focus=on center=on state=floating
bspc rule -a kitty:*:scratchpad sticky=on state=floating rectangle=1600x280+160+38
# bspc rule -a Florence sticky=on state=floating rectangle=1600x400+160+660 focus=off manage=off
# bspc rule -a Xfce4-panel layer=below

export QT_STYLE_OVERRIDE=kvantum

# if [[ $1 -gt 0 ]];
# then
# [[ -z $(pidof plank) ]] && plank || pkill plank ; plank &
# else
#   xfce4-terminal & plank &
# fi

setxkbmap -option "caps:escape" &
#xfce4-panel -d -r&
#xrdb -load ~/.config/xorg/xresources &
#xfdesktop & 
#xfce4-power-manager &
#xfce4-clipman &
#xfce4-screensaver &
#libinput-gestures &
#start-pulseaudio-x11 &
#/usb/lib/xfce4/notifyd/xfce4-notifyd &
#pkill unclutter; unclutter --timeout 4 &
#light-locker &
#nm-applet &
#xfdesktop &
#blueman-applet &
#pkill emoji-keyboard; emoji-keyboard &
kupfer --no-splash &
xsetroot -cursor_name left_ptr &
bspc config -d 1
picom --config ~/.config/picom/picomrc --experimental -d -b &
gnome-pie &
feh --bg-scale ~/Pictures/Wallpapers/wall.png &

