#!/bin/sh
#           _                   _     _       _ 
#  ___  ___| |____     _____  _| |__ | | ____| |
# / __|/ _ \ |_  /____/ __\ \/ / '_ \| |/ / _` |
# \__ \  __/ |/ /_____\__ \>  <| | | |   < (_| |
# |___/\___|_/___|    |___/_/\_\_| |_|_|\_\__,_|

super + Return
 kitty

super + 1
  jumpapp ~/.local/bin/script/chrome

super + shift + 1
  ~/.local/bin/script/chrome

super + 2
  jumpapp nautilus

super + shift + 2
  nautilus

super + 3
  jumpapp kitty

super + shift + 3
  kitty

super + 4
  jumpapp code

super + shift + 4
  code

super + Delete
  betterlockscreen -l
   
super + {_,shift + } Tab
  bspc node -f {next,prev}.!hidden.window

super + {h,j,k,l}
	bspc node -f {west,south,north,east}
  
super + shift + {h,j,k,l}
  ~/.local/bin/script/bspwm/move-window {left,down,up,right}

super + f
  ~/.local/bin/script/bspwm/node-monocle

super + shift + F
  ~/.local/bin/script/bspwm/node-fullscreen

super + d
  ~/.local/bin/script/bspwm/node-floating

super + v
  ~/.local/bin/script/bspwm/show-clipman

super + {_,shift + }w
	~/.local/bin/script/bspwm/quit-node {c,k}

# screenshots

Print
  xfce4-screenshooter -f --clipboard

shift + Print
  xfce4-screenshooter -r --clipboard

ctrl + Print
   xfce4-screenshooter -f --save ~/Pictures/Screenshots
 
ctrl + shift + Print
  xfce4-screenshooter -r --save ~/Pictures/Screenshots

super + Print
  xfce4-screenshooter

super + alt + Print
  peek

XF86AudioRaiseVolume
  amixer set Master 5%+ 1>/dev/null

# Decrease volume
XF86AudioLowerVolume
  amixer set Master 5%- 1>/dev/null

# Mute Audio
XF86AudioMute
  amixer -D pulse set Master 1+ toggle 1>/dev/null

XF86AudioMicMute
  amixer -D pulse set Capture 1+ toggle 1>/dev/null

super + Down
  playerctl play-pause

super + Left
  playerctl previous

super + Right
  playerctl next

XF86MonBrightnessUp
  brightnessctl s +5%

XF86MonBrightnessDown
  [[ $(brightnessctl g) -gt 91 ]] && brightnessctl s 5%-

super + F5
  ~/.local/bin/script/switchBacklight

super + r
	kupfer

super + Escape
	pkill -USR1 -x sxhkd

super + backslash
  ~/.local/bin/script/bspwm/scratchpad

super + {comma,period}
	bspc desktop -f {prev,next}.local

super + shift + {comma,period}
  bspc node -d {prev,next}.local --follow;

super + alt + {q,r}
	bspc {quit,wm -r}

super + g
	bspc node -s biggest.window

# super + {_,shift + }{1-6}
# 	bspc {desktop -f,node -d} '^{1-6}'

# super + ctrl + {h,j,k,l}
# 	bspc node -p {west,south,north,east}

# super + ctrl + space
# 	bspc node -p cancel

super + alt + {h,j,k,l}
  n=20; \
  { d1=left;   d2=right;  dx=-$n; dy=0;   \
  , d1=bottom; d2=top;    dx=0;   dy=$n;  \
  , d1=top;    d2=bottom; dx=0;   dy=-$n; \
  , d1=right;  d2=left;   dx=$n;  dy=0;   \
  }\
  bspc node --resize $d1 $dx $dy || bspc node --resize $d2 $dx $dy

super + alt + shift + {l,k,j,h}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}
